---
# Test filter_plugins/dict_utils filter:prefix_key

- hosts: localhost
  gather_facts: no

  vars:
    ports:
      webui: 7200
      webadmin: 7209
      core_api: 7201
      stock_api: 7204
      import_export: 7207


  tasks:
    - debug:
        var: staging_ports
      vars:
        staging_ports: "{{ ports|prefix_key(prefix='staging_') }}"
...
