---
# Test filter_plugins/dict_utils

- hosts: localhost
  gather_facts: no

  vars:
    dict1:
      a: 1
      b: 2
    dict2:
      a: 1
      b: 2
      c: 3
    dict3:
      a: [1]
      b: [2]
      c: [3]
    add_this:
      c: 9
    ports:
      webui: 7200
      webadmin: 7209
      core_api: 7201
      stock_api: 7204
      import_export: 7207


  tasks:
    - debug:
        var: added_hash
      vars:
        added_hash: "{{ dict1|dict_add_hash(add_this) }}"
      tags: added_hash
    - debug:
        var: appended_hash
      vars:
        appended_hash: "{{ dict2|dict_add_hash(add_this, True) }}"
      tags: appended_hash
    - debug:
        var: replaced_hash
      vars:
        replaced_hash: "{{ dict2|dict_add_hash(add_this) }}"
      tags: replaced_hash
    - debug:
        var: appended_hash_to_list
      vars:
        appended_hash_to_list: "{{ dict3|dict_add_hash(add_this, True) }}"
      tags: appended_hash_to_list
    - debug:
        var: prefixed_keys
      vars:
        prefixed_keys: "{{ ports|dict_prefix_keys('staging_') }}"
      tags: prefixed_keys
