---
# Test filter_plugins/dict_utils

- name: dict_utils
  hosts: localhost
  gather_facts: no

  vars:
    dict1:
      a: 1
      b: 2
    dict2:
      a: 1
      b: 2
      c: 3
    dict3:
      a: [1]
      b: [2]
      c: [3]
    add_this:
      c: 9
    ports:
      webui: 7200
      webadmin: 7209
      core_api: 7201
      stock_api: 7204
      import_export: 7207
    dict4: {
      "a":{
        "r": 1,
        "s": 2,
        "t": 3
        },
      "b":{
        "u": 1,
        "v": {
            "x": 1,
            "y": 2,
            "z": [ 3, 4, 5 ]
          },
        "w": 3
        }
      }


  tasks:
    - debug:
        var: merge_dict
      vars:
        merge_dict: "{{ dict1|dict_merge(dict2) }}"
      tags: merge_dict
    - debug:
        var: merge_dict
      vars:
        merge_dict: "{{ dict1|dict_merge(dict3) }}"
      tags: merge_dict
    - debug:
        var: added_hash
      vars:
        added_hash: "{{ dict1|dict_add_hash(add_this) }}"
      tags: added_hash
    - debug:
        var: appended_hash
      vars:
        appended_hash: "{{ dict2|dict_add_hash(add_this, True) }}"
      tags: appended_hash
    - debug:
        var: replaced_hash
      vars:
        replaced_hash: "{{ dict2|dict_add_hash(add_this) }}"
      tags: replaced_hash
    - debug:
        var: appended_hash_to_list
      vars:
        appended_hash_to_list: "{{ dict3|dict_add_hash(add_this, True) }}"
      tags: appended_hash_to_list
    - debug:
        var: prefixed_keys
      vars:
        prefixed_keys: "{{ ports|dict_prefix_keys('staging_') }}"
      tags: prefixed_keys
    - debug:
        var: dict4_flatten
      vars:
        dict4_flatten: "{{ dict4|dict_flatten('.') }}"
      tags: dict_flatten
