---
# Test filter_plugins/numpy_filters

- name: numpy_filters
  hosts: localhost
  gather_facts: false

  vars:

    arr1:
      - [1, 2, 3]
      - [4, 5, 6]
      - [7, 8, 9]

    arr2:
      - [1, 4, 7]
      - [2, 5, 8]
      - [3, 6, 9]

    arr3: [a, b, c, d, e]
    idx: [1, 3, 4]

  tasks:

    # numpy_transpose
    - block:
        - debug:
            var: arr1|to_yaml
          when: debug|d(false)|bool
        - debug:
            var: arr|to_yaml
          when: debug|d(false)|bool
        - name: numpy_transpose
          assert:
            that: arr == result
      vars:
        arr: "{{ arr1|numpy_transpose }}"
        result:
          - [1, 4, 7]
          - [2, 5, 8]
          - [3, 6, 9]
      tags: numpy_transpose

    # numpy_array_by_idx
    - block:
        - debug:
            var: arr3|to_yaml
          when: debug|d(false)|bool
        - debug:
            var: idx|to_yaml
          when: debug|d(false)|bool
        - debug:
            var: arr|to_yaml
          when: debug|d(false)|bool
        - name: numpy_array_by_idx
          assert:
            that: arr == result
      vars:
        arr: "{{ arr3|numpy_array_by_idx(idx) }}"
        result: [b, d, e]
      tags: numpy_array_by_idx

# EOF
...
