---

- name: string_filters
  hosts: localhost
  gather_facts: no
  vars:
    input: [ "a", "b", "c" ]
  tasks:
    - debug:
        msg: "{{ lookup('file', 'test.txt')|string_count('phrase') }}"
    - debug:
        msg: "{{ lookup('file', 'test.txt')|string_find('phrase') }}"
    - debug:
        msg: "{{ 'abc'|string_postfix('-postfix') }}"
    - debug:
        msg: "{{ 'abc'|string_prefix('prefix-') }}"
    - set_fact:
        output: "{{ input|map('string_prefix', 'prefix-')|list }}"
    - debug:
        var: output
    - set_fact:
        output: "{{ input|map('string_postfix', '-postfix')|list }}"
    - debug:
        var: output
...
